[colors.primary]
background = "#0d1117"
foreground = "#f0f6fc"

[colors.cursor]
text = "#0d1117"
cursor = "#f0f6fc"

[colors.vi_mode_cursor]
text = "#0d1117"
cursor = "#f0f6fc"

[colors.search.matches]
foreground = "#0d1117"
background = "#f0f6fc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#484f58"
background = "#f0f6fc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0d1117"
red = "#ff7b72"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[colors.bright]
black = "#484f58"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#f0f6fc"

[colors.dim]
black = "#f0f6fc"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#484f58"
